baseURL = "https://prthmptl.github.io/"
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"

[params]
  author = "Pratham Patel"
  description = "Portfolio & Blog by Pratham Patel"
  ShowReadingTime = true
  ShowToc = true
  TocOpen = false

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4
